/*
 * apu/mp3dec.h -- an MPEG-1/2/2.5 audio Layer III decoder.
 *
 * Written for MultiStream's MP3 streams (src/apu/mp3_native.c), to the
 * standard (ISO/IEC 11172-3, 13818-3); the constant tables are generated by
 * tools/gen_mp3_tables.py. One call decodes one whole frame. The state is
 * plain data, so the caller can keep it anywhere (MultiStream keeps it in
 * the SPU local store, per stream and per channel).
 */
#ifndef DOD3_MP3DEC_H
#define DOD3_MP3DEC_H
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    float overlap[32][18];   /* the IMDCT's second half, added to the next granule */
    float synth[16][32];     /* the last 16 matrixed vectors (32 values each) */
} dod3_mp3_channel;

typedef struct {
    dod3_mp3_channel ch[2];
    int32_t synth_pos;       /* ring position in synth[], both channels */
    int32_t reserv_len;      /* bytes of main data kept for the next frame */
    uint8_t reserv[512];     /* the bit reservoir: the main data stream's tail */
} dod3_mp3;

typedef struct {
    int frame_bytes;         /* the whole frame, header included */
    int channels;
    int samples;             /* per channel: 1152 (MPEG-1) or 576 */
    int hz;
} dod3_mp3_info;

/* The frame's length from its 4-byte header, filling info; 0 if it is not
 * a Layer III header this decoder handles (free format is not). */
int dod3_mp3_frame_bytes(const uint8_t* hdr, dod3_mp3_info* info);

/* Decode the frame at `frame` (frame_bytes long). Writes info->samples
 * samples per channel to out[0] (and out[1] if stereo) and returns that
 * count; -1 if the frame is invalid (nothing written, state unchanged). A
 * frame whose main data starts in bytes the reservoir no longer holds (the
 * first frames after a seek) decodes as silence. A zeroed dod3_mp3 is a
 * decoder at the start of a stream. */
int dod3_mp3_decode(dod3_mp3* d, const uint8_t* frame, int16_t* out[2], dod3_mp3_info* info);

#ifdef __cplusplus
}
#endif
#endif
