#!/usr/bin/env python3
"""gen_libsre_lfqueue.py -- lift the real libsre LFQueue push path into a C++ TU.

Drakengard 3 feeds its SPU zlib task through a SPURS LFQueue created ANY2ANY.
The SPU end is the game's own lifted code, which pops the queue straight out of
guest memory with lock-line atomics, so the PPU end has to speak exactly the
same protocol. Nobody has documented the ANY2ANY variant (RPCS3 leaves
_cellSyncLFQueueGetPushPointer2/CompletePushPointer2 as TODO), so instead of a
hand port this lifts Sony's own implementation out of libsre.prx:

    0x010024F4  _cellSyncLFQueueGetPushPointer
    0x01002708  _cellSyncLFQueueCompletePushPointer
    0x010030B8  _cellSyncLFQueueGetPushPointer2       (ANY2ANY)
    0x010035C8  _cellSyncLFQueueCompletePushPointer2  (ANY2ANY)

plus every libsre function they reach. Those functions only touch the queue
line through r3, never libsre's own data, so they run unchanged against the
game's guest memory. Two things are rewritten:

  * calls into libsre's import stubs (0x0101D718..0x0101DB18) only occur on
    assertion-failure paths (_sys_printf + _sys_trap_process) and become
    dod3_libsre_import_trap();
  * the one indirect call -- fpSendSignal, made through an OPD in libsre's
    address space -- becomes dod3_lfq_send_signal(), which signals the task
    through the HLE SPURS.

The output is derived from firmware, so it is written to the build tree and
never committed.

usage: gen_libsre_lfqueue.py <ps3recomp dir> <libsre.prx> <work dir> <out .cpp>
"""
import re
import subprocess
import sys
from pathlib import Path

BASE = 0x01000000
TOC = 0x01039AB0
ROOTS = [0x010024F4, 0x01002708, 0x010030B8, 0x010035C8]
STUBS = range(0x0101D718, 0x0101DB18)
FUNC_RE = re.compile(r"^void libsre_func_([0-9A-F]{8})\(ppu_context\* ctx\) \{$")
CALL_RE = re.compile(r"libsre_func_([0-9A-F]{8})\(ctx\)")


def run(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode:
        sys.exit(f"gen_libsre_lfqueue: {' '.join(map(str, cmd))} failed:\n{r.stdout}{r.stderr}")


def main():
    if len(sys.argv) != 5:
        sys.exit(__doc__)
    toolkit, prx, work, out = map(Path, sys.argv[1:])
    work.mkdir(parents=True, exist_ok=True)
    py = sys.executable

    run([py, toolkit / "tools/lift_prx.py", prx, "--base", hex(BASE), "-o", work])
    run([py, toolkit / "tools/ppu_lifter.py", work / "libsre_image.bin", "--raw",
         "--base", hex(BASE), "--toc", hex(TOC),
         "--functions", work / "libsre_functions.json",
         "--symbol-prefix", "libsre_", "-o", work / "lifted"])

    lines = (work / "lifted/ppu_recomp_000.cpp").read_text().splitlines()

    # Split into prelude + {addr: body lines}.
    funcs, prelude, cur = {}, [], None
    for ln in lines:
        m = FUNC_RE.match(ln)
        if m:
            cur = int(m.group(1), 16)
            funcs[cur] = [ln]
            continue
        if cur is None:
            prelude.append(ln)
        elif funcs[cur][-1] != "}":
            funcs[cur].append(ln)
    for a, body in funcs.items():
        if body[-1] != "}":
            sys.exit(f"gen_libsre_lfqueue: function 0x{a:08X} has no closing brace")

    # Transitive closure from the roots, stopping at import stubs.
    need, todo = set(), list(ROOTS)
    while todo:
        a = todo.pop()
        if a in need or a in STUBS:
            continue
        if a not in funcs:
            sys.exit(f"gen_libsre_lfqueue: callee 0x{a:08X} was not lifted")
        need.add(a)
        for ln in funcs[a]:
            for m in CALL_RE.finditer(ln):
                todo.append(int(m.group(1), 16))

    out_lines = [
        "/* GENERATED by tools/gen_libsre_lfqueue.py from libsre.prx -- do not edit,",
        " * do not commit (firmware-derived). */",
    ]
    out_lines += prelude
    out_lines.append("")
    out_lines.append('extern "C" void dod3_libsre_import_trap(ppu_context* ctx);')
    out_lines.append('extern "C" void dod3_lfq_send_signal(ppu_context* ctx);')
    for a in sorted(need):
        out_lines.append(f"void libsre_func_{a:08X}(ppu_context* ctx);")
    out_lines.append("")

    # The only indirect calls in the push path are the fpSendSignal calls: one in
    # CompletePushPointer, one in the ANY2ANY waiter-wake loop. Anything else
    # means the closure grew and needs a look before it is trusted.
    signal_sites = {0x01002708, 0x0100439C}
    indirect = set()
    for a in sorted(need):
        for ln in funcs[a]:
            for m in list(CALL_RE.finditer(ln)):
                t = int(m.group(1), 16)
                if t in STUBS:
                    ln = ln.replace(m.group(0), "dod3_libsre_import_trap(ctx)")
            if "ps3_indirect_call(ctx)" in ln:
                if a not in signal_sites:
                    sys.exit(f"gen_libsre_lfqueue: unexpected indirect call in 0x{a:08X}")
                ln = ln.replace("ps3_indirect_call(ctx)", "dod3_lfq_send_signal(ctx)")
                indirect.add(a)
            out_lines.append(ln)
        out_lines.append("")

    if indirect != signal_sites:
        sys.exit(f"gen_libsre_lfqueue: fpSendSignal sites moved: {sorted(map(hex, indirect))}")

    # One entry point for the hand-written side, so it needs neither the lifted
    # names nor the prelude's DRAIN_TRAMPOLINE. Returns 0 for an unknown root.
    out_lines.append('extern "C" int dod3_libsre_call(uint32_t addr, ppu_context* ctx)')
    out_lines.append("{")
    out_lines.append("    switch (addr) {")
    for a in ROOTS:
        out_lines.append(f"    case 0x{a:08X}u: libsre_func_{a:08X}(ctx); break;")
    out_lines.append("    default: return 0;")
    out_lines.append("    }")
    out_lines.append("    DRAIN_TRAMPOLINE(ctx);")
    out_lines.append("    return 1;")
    out_lines.append("}")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(out_lines) + "\n")
    print(f"gen_libsre_lfqueue: {len(need)} functions -> {out}")


if __name__ == "__main__":
    main()
