#!/usr/bin/env python3
"""gen_libsre.py -- lift parts of the real libsre (cellSpurs/cellSync) into a C++ TU.

Some SPURS primitives are shared with lifted SPU code, which reads and writes
them straight out of guest memory with lock-line atomics, so the PPU side has
to speak Sony's protocol exactly. Where the toolkit's HLE does not -- or has no
implementation at all -- this lifts Sony's own code out of libsre.prx instead
of guessing at a hand port:

  SPURS LFQueue push (Drakengard 3's zlib task; ANY2ANY, which RPCS3 leaves TODO)
    0x010024F4  _cellSyncLFQueueGetPushPointer
    0x01002708  _cellSyncLFQueueCompletePushPointer
    0x010030B8  _cellSyncLFQueueGetPushPointer2
    0x010035C8  _cellSyncLFQueueCompletePushPointer2
  SPURS queue
    0x010164C0  _cellSpursQueueInitialize
    0x010169D0  cellSpursQueuePushBody
    0x01016CFC  cellSpursQueuePopBody

plus every libsre function they reach. They touch only the structures they are
handed, never libsre's own data (TOC reads occur on assertion paths alone), so
they run unchanged against the game's guest memory. Rewritten:

  * calls to libsre internals with an HLE counterpart (HOOKS): sending a task
    signal and finding a workload's taskset go to the toolkit's SPURS, and the
    assertion reporters trap;
  * calls into libsre's import stubs (STUB_HOOKS): _sys_memcpy is real work,
    every other import is reached only on an assertion path and traps;
  * the fpSendSignal indirect calls in the LFQueue path.

The output is derived from firmware, so it is written to the build tree and
never committed.

usage: gen_libsre.py <ps3recomp dir> <libsre.prx> <work dir> <out .cpp>
"""
import re
import subprocess
import sys
from pathlib import Path

BASE = 0x01000000
TOC = 0x01039AB0
ROOTS = [
    0x010024F4, 0x01002708, 0x010030B8, 0x010035C8,     # LFQueue push
    0x010164C0, 0x010169D0, 0x01016CFC,                 # SPURS queue
]
HOOKS = {
    0x010125D8: "dod3_spurs_send_signal",       # _cellSpursSendSignal(taskset, taskId)
    0x010134B8: "dod3_spurs_workload_taskset",  # (spurs, &taskset, wid)
    0x01012F6C: "dod3_libsre_import_trap",      # queue assertion reporters
    0x0101309C: "dod3_libsre_import_trap",
}
STUBS = range(0x0101D718, 0x0101DB18)
STUB_HOOKS = {
    0x0101D8F8: "dod3_libsre_memcpy",           # sysPrxForUser _sys_memcpy
}
# Indirect calls are fpSendSignal and nothing else; anything new needs a look.
SIGNAL_SITES = {0x01002708, 0x0100439C}
FUNC_RE = re.compile(r"^void libsre_func_([0-9A-F]{8})\(ppu_context\* ctx\) \{$")
CALL_RE = re.compile(r"libsre_func_([0-9A-F]{8})\(ctx\)")


def run(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode:
        sys.exit(f"gen_libsre: {' '.join(map(str, cmd))} failed:\n{r.stdout}{r.stderr}")


def hook_for(target):
    if target in HOOKS:
        return HOOKS[target]
    if target in STUBS:
        return STUB_HOOKS.get(target, "dod3_libsre_import_trap")
    return None


def main():
    if len(sys.argv) != 5:
        sys.exit(__doc__)
    toolkit, prx, work, out = map(Path, sys.argv[1:])
    work.mkdir(parents=True, exist_ok=True)
    py = sys.executable

    run([py, toolkit / "tools/lift_prx.py", prx, "--base", hex(BASE), "-o", work])
    run([py, toolkit / "tools/ppu_lifter.py", work / "libsre_image.bin", "--raw",
         "--base", hex(BASE), "--toc", hex(TOC),
         "--functions", work / "libsre_functions.json",
         "--symbol-prefix", "libsre_", "-o", work / "lifted"])

    lines = (work / "lifted/ppu_recomp_000.cpp").read_text().splitlines()

    # Split into prelude + {addr: body lines}.
    funcs, prelude, cur = {}, [], None
    for ln in lines:
        m = FUNC_RE.match(ln)
        if m:
            cur = int(m.group(1), 16)
            funcs[cur] = [ln]
            continue
        if cur is None:
            prelude.append(ln)
        elif funcs[cur][-1] != "}":
            funcs[cur].append(ln)
    for a, body in funcs.items():
        if body[-1] != "}":
            sys.exit(f"gen_libsre: function 0x{a:08X} has no closing brace")

    # Transitive closure from the roots, stopping at hooked calls.
    need, todo = set(), list(ROOTS)
    while todo:
        a = todo.pop()
        if a in need or hook_for(a):
            continue
        if a not in funcs:
            sys.exit(f"gen_libsre: callee 0x{a:08X} was not lifted")
        need.add(a)
        for ln in funcs[a]:
            for m in CALL_RE.finditer(ln):
                todo.append(int(m.group(1), 16))

    hooks = sorted(set(HOOKS.values()) | set(STUB_HOOKS.values())
                   | {"dod3_libsre_import_trap", "dod3_lfq_send_signal"})
    out_lines = [
        "/* GENERATED by tools/gen_libsre.py from libsre.prx -- do not edit,",
        " * do not commit (firmware-derived). */",
    ]
    out_lines += prelude
    out_lines.append("")
    out_lines += [f'extern "C" void {h}(ppu_context* ctx);' for h in hooks]
    out_lines += [f"void libsre_func_{a:08X}(ppu_context* ctx);" for a in sorted(need)]
    out_lines.append("")

    indirect = set()
    for a in sorted(need):
        for ln in funcs[a]:
            for m in list(CALL_RE.finditer(ln)):
                h = hook_for(int(m.group(1), 16))
                if h:
                    ln = ln.replace(m.group(0), f"{h}(ctx)")
            if "ps3_indirect_call(ctx)" in ln:
                if a not in SIGNAL_SITES:
                    sys.exit(f"gen_libsre: unexpected indirect call in 0x{a:08X}")
                ln = ln.replace("ps3_indirect_call(ctx)", "dod3_lfq_send_signal(ctx)")
                indirect.add(a)
            out_lines.append(ln)
        out_lines.append("")

    if indirect != SIGNAL_SITES:
        sys.exit(f"gen_libsre: fpSendSignal sites moved: {sorted(map(hex, indirect))}")

    # One entry point for the hand-written side, so it needs neither the lifted
    # names nor the prelude's DRAIN_TRAMPOLINE. Returns 0 for an unknown root.
    out_lines.append('extern "C" int dod3_libsre_call(uint32_t addr, ppu_context* ctx)')
    out_lines.append("{")
    out_lines.append("    switch (addr) {")
    for a in ROOTS:
        out_lines.append(f"    case 0x{a:08X}u: libsre_func_{a:08X}(ctx); break;")
    out_lines.append("    default: return 0;")
    out_lines.append("    }")
    out_lines.append("    DRAIN_TRAMPOLINE(ctx);")
    out_lines.append("    return 1;")
    out_lines.append("}")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(out_lines) + "\n")
    print(f"gen_libsre: {len(need)} functions -> {out}")


if __name__ == "__main__":
    main()
