#!/usr/bin/env python3
"""make_spu_overlays.py -- MultiStream DSP plugins, lifted where they actually run.

The MultiStream mixer task (spu_0000) runs small position-independent SPU
programs -- DSP plugins -- out of its own local store. They are ordinary SPU
ELFs in the EBOOT, linked at 0x80, which extract_spu_images.py already finds.
At run time MultiStream copies their text, packed back to back, into one heap
block and GETs the whole block into the mixer's plugin area at LS 0x37000.

Lifted code is only right at the address it was lifted for (a PIC module
derives its data addresses from its own return address, and the lifter turns
that into a constant), so the block is rebuilt here exactly as MultiStream
lays it out, lifted once at 0x37000, and registered as an overlay recognised
by its first 16 bytes -- the heap copy's address differs from run to run.

  wrap     write spu/images/spu_ovl_msdsp_37000.elf and print the extra
           function seeds build_spu_workloads.py needs (--extra-funcs)
  register write spu/spu_overlays.c with the image id build_spu_workloads.py
           assigned (run after it)

The layout comes from a dump of that GET (SPU_DUMP_OVL=<dir>,0x37000). A
different plugin set or order would arrive with a different signature and
miss, and the runtime would report the branch into unlifted LS.
"""
import re
import struct
import sys
from pathlib import Path

BLOCK_LSA = 0x37000
NAME = "spu_ovl_msdsp_37000"
# (source SPU ELF, offset of its text in the block)
PLUGINS = [
    ("spu_0027_at_018F7C00", 0x0000),
    ("spu_0029_at_018FC300", 0x2000),
    ("spu_0037_at_01904F80", 0x2900),
]


def text_segment(elf):
    entry, phoff = struct.unpack(">II", elf[0x18:0x20])
    phn, = struct.unpack(">H", elf[0x2C:0x2E])
    for i in range(phn):
        o = phoff + i * 32
        p_type, off, va, _pa, fsz, _msz, flags, _al = struct.unpack(">8I", elf[o:o + 32])
        if p_type == 1 and flags & 1:
            return entry, va, elf[off:off + fsz]
    sys.exit("make_spu_overlays: no executable PT_LOAD")


def build_block(images):
    block, entries = bytearray(), []
    for module, at in PLUGINS:
        entry, va, code = text_segment((images / f"{module}.elf").read_bytes())
        if len(block) > at:
            sys.exit(f"make_spu_overlays: {module} overlaps the previous plugin")
        block += bytes(at - len(block)) + code
        entries.append(BLOCK_LSA + at + (entry - va))
        # Every plugin opens with a 16-byte signature and then the entry the
        # host calls through, at +0x10. Nothing inside the module branches
        # there, so the lifter only finds it as a seed.
        entries.append(BLOCK_LSA + at + 0x10)
        # The rest of a plugin's interface is a table of callbacks it hands the
        # mixer, computed position-independently, so no branch in the image
        # names them. Functions are laid out back to back, so seed the first
        # real instruction after every return (bi $r0), skipping alignment
        # padding. A false start costs one extra, never-called function.
        entries += [BLOCK_LSA + at + o for o in after_returns(code)]
    return bytes(block), entries


BI_R0, NOP, LNOP = 0x35000000, 0x4020007F, 0x00200000


def after_returns(code):
    words = struct.unpack(f">{len(code) // 4}I", code[:len(code) // 4 * 4])
    out = []
    for i, w in enumerate(words):
        if w != BI_R0:
            continue
        j = i + 1
        while j < len(words) and words[j] in (NOP, LNOP):
            j += 1
        if j < len(words) and words[j] != 0:
            out.append(j * 4)
    return out


def wrap(root):
    sys.path.insert(0, str(root / "ps3recomp/tools"))
    from wrap_spu_elf import wrap as wrap_elf
    images = root / "spu/images"
    block, entries = build_block(images)
    (images / f"{NAME}.elf").write_bytes(wrap_elf(block, base=BLOCK_LSA, entry=entries[0]))
    print(f"--extra-funcs {NAME}=" + ",".join(f"0x{e:X}" for e in sorted(set(entries[1:]))))


def register(root):
    workloads = (root / "spu/spu_workloads.c").read_text()
    m = re.search(r"spu_begin_image\((\d+)\); " + re.escape(NAME) + r"_spu_recomp_register", workloads)
    if not m:
        sys.exit(f"make_spu_overlays: {NAME} is not in spu_workloads.c -- run build_spu_workloads.py first")
    block, _ = build_block(root / "spu/images")
    sig = ", ".join(f"0x{b:02X}" for b in block[:16])
    (root / "spu/spu_overlays.c").write_text(f"""\
/* spu_overlays.c - GENERATED by tools/make_spu_overlays.py. */
#include <stdint.h>

extern void spu_overlay_register_sig_region(const uint8_t sig[16], uint32_t span, int image_id);

__attribute__((constructor)) static void dod3_spu_overlays_register(void)
{{
    static const uint8_t sig[16] = {{ {sig} }};
    spu_overlay_register_sig_region(sig, 0x{len(block):X}u, {m.group(1)});  /* {NAME} */
}}
""")
    print(f"make_spu_overlays: wrote spu/spu_overlays.c ({NAME} = image {m.group(1)})")


if __name__ == "__main__":
    if len(sys.argv) != 2 or sys.argv[1] not in ("wrap", "register"):
        sys.exit(__doc__)
    root = Path(__file__).resolve().parent.parent
    {"wrap": wrap, "register": register}[sys.argv[1]](root)
